# Generated by Django 3.2.8 on 2021-11-05 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Users',
        ),
    ]
