# Generated by Django 3.2.8 on 2021-11-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0002_rename_product_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Registered_User',
        ),
    ]
