# Generated by Django 3.2.8 on 2021-11-05 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0004_auto_20211105_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registered_user',
            old_name='Password',
            new_name='password',
        ),
    ]
