# Generated by Django 3.2.8 on 2021-11-05 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0007_reservstions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservstions',
            new_name='Reservations',
        ),
    ]
