# Generated by Django 3.2.8 on 2021-11-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0009_rename_reservations_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='Reserved',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
