# Generated by Django 3.2.8 on 2021-11-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0010_reservation_reserved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='Court_Type',
        ),
        migrations.AddField(
            model_name='reservation',
            name='Court_Types',
            field=models.CharField(choices=[('A', 'Hard'), ('B', 'Clay'), ('C', 'Grass')], default=True, max_length=1),
            preserve_default=False,
        ),
    ]
