# Generated by Django 3.2.8 on 2021-11-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0011_auto_20211106_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered_user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
