# Generated by Django 3.2.8 on 2021-11-06 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0012_alter_registered_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registered_user',
            old_name='id',
            new_name='User_id',
        ),
    ]
