# Generated by Django 3.2.8 on 2021-11-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0013_rename_id_registered_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered_user',
            name='User_id',
            field=models.AutoField(db_column='BID', primary_key=True, serialize=False),
        ),
    ]
