# Generated by Django 3.2.8 on 2021-11-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0014_alter_registered_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('Phone_No', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
