# Generated by Django 3.2.8 on 2021-11-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0015_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='Club_Id',
            new_name='Court_Id',
        ),
    ]
