# Generated by Django 3.2.8 on 2021-11-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0016_rename_club_id_reservation_court_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='Court_Person',
            field=models.CharField(max_length=20),
        ),
    ]
