# Generated by Django 3.2.8 on 2021-11-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0020_delete_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Court_Types', models.CharField(max_length=50)),
                ('Court_Person', models.CharField(max_length=50)),
                ('Court_Id', models.IntegerField(unique=True)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Reserved', models.BooleanField()),
            ],
        ),
    ]
