# Generated by Django 3.2.8 on 2021-11-06 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0021_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='Court_Person',
        ),
    ]
