# Generated by Django 3.2.8 on 2021-11-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0028_alter_registered_user_member_availed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered_user',
            name='Membership_End_Time',
            field=models.DateField(verbose_name='0000-00-00'),
        ),
        migrations.AlterField(
            model_name='registered_user',
            name='Membership_Start_time',
            field=models.DateField(verbose_name='0000-00-00'),
        ),
    ]
