# Generated by Django 3.2.8 on 2021-11-07 12:51

import club_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0029_auto_20211107_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered_user',
            name='Membership_End_Time',
            field=models.DateField(default=club_app.models.default_start_time),
        ),
        migrations.AlterField(
            model_name='registered_user',
            name='Membership_Start_time',
            field=models.DateField(default=club_app.models.default_start_time),
        ),
    ]
