# Generated by Django 3.2.8 on 2021-11-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0032_alter_registered_user_member_availed'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Phone_num', models.CharField(max_length=12)),
                ('Message', models.CharField(max_length=500)),
            ],
        ),
    ]
