# Generated by Django 3.2.8 on 2021-11-21 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0033_contact_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=100)),
                ('Appling_Fee', models.IntegerField(default=0)),
                ('Date', models.DateField(default=datetime.date.today)),
                ('image', models.ImageField(default='', upload_to='club_app/images')),
            ],
        ),
    ]
