# Generated by Django 3.2.8 on 2021-11-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0036_events_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered_user',
            name='Applied_event',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
