# Generated by Django 3.2.8 on 2021-11-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0039_auto_20211122_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
