# Generated by Django 3.2.8 on 2021-11-22 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0040_alter_room_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
