# Generated by Django 3.2.8 on 2021-11-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0043_auto_20211127_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Experience', models.IntegerField()),
                ('star_2', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('suggestion', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='contact_us',
        ),
    ]
