# Generated by Django 3.2.8 on 2021-11-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0044_auto_20211128_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user_email',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
