# Generated by Django 3.2.8 on 2021-11-27 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0048_alter_feedback_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user_email',
        ),
    ]
