# Generated by Django 3.2.8 on 2021-11-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0049_remove_feedback_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user_email',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
