# Generated by Django 3.2.8 on 2021-12-02 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0054_auto_20211202_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered_user',
            name='Membership_End_time',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='registered_user',
            name='Membership_Start_time',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
