# Generated by Django 3.2.8 on 2021-12-02 14:54

import club_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0058_auto_20211202_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered_user',
            name='Membership_End_time',
            field=models.DateField(default=club_app.models.default_start_time),
        ),
        migrations.AlterField(
            model_name='registered_user',
            name='Membership_Start_time',
            field=models.DateField(default=club_app.models.default_start_time),
        ),
    ]
