# Generated by Django 3.2.8 on 2021-12-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0059_auto_20211202_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='id',
        ),
        migrations.AddField(
            model_name='reservation',
            name='Reservation_Id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
