# Generated by Django 3.2.8 on 2021-12-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0061_auto_20211202_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('reser_id', models.IntegerField()),
                ('original_amount', models.IntegerField()),
                ('paid_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment',
            field=models.IntegerField(default=0),
        ),
    ]
