# Generated by Django 3.2.8 on 2021-12-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0063_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
    ]
